name: example
description: Examples how to use ThemeTailor
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^5.7.1
  collection: ^1.16.0
  flutter:
    sdk: flutter

  json_annotation: ^4.7.0
  theme_tailor_annotation: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.3.2
  theme_tailor: ^1.2.0

flutter:
  uses-material-design: true
