name: theme_tailor
description: Theme Tailor generator. Theming utility
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  analyzer: ^4.1.0
  args: ^2.3.1
  build: ^2.3.0
  build_config: ^1.0.0
  collection: ^1.16.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  path: ^1.8.1
  source_gen: ^1.2.2
  theme_tailor_annotation:
    path: ../theme_tailor_annotation

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  source_gen_test: ^1.0.3
  test: ^1.21.1
