name: theme_tailor
description: >
  Code generator for Flutter's 3.0 ThemeExtension classes. 
  The generator can create themes and extensions on BuildContext 
  or ThemeData based on the lists of the theme properties
version: 1.1.1-dev
repository: https://github.com/Iteo/theme_tailor
issue_tracker: https://github.com/Iteo/theme_tailor/issues
homepage: https://github.com/Iteo/theme_tailor
documentation: https://github.com/Iteo/theme_tailor/blob/main/packages/theme_tailor/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build_config: ^1.1.0
  build: ^2.3.1
  collection: ^1.15.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  source_gen: ^1.2.3
  source_helper: ^1.3.2
  theme_tailor_annotation: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1

screenshots:
  - description: Package logo
    path: screenshots/logo.png
