name: theme_tailor_figma_loader
description: Flutter package that simplifies generator style from figma.
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  args: ^2.3.1
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
